---
- name: Determine latest stage tarball
  uri:
    url: "{{ gentoo_install_baseurl }}{{ gentoo_install_latest_stage_pointer }}"
    return_content: yes
  register: latest_stage
  tags:
    - filesystem

- set_fact:
    latest_stage_tarball_url_suffix: "{{ ( latest_stage.content.splitlines() | reject('match', '#') | first ).split(' ')[0] }}"
    latest_stage_tarball: "{{ ( latest_stage.content.splitlines() | reject('match', '#') | first ).split(' ')[0].split('/')[1] }}"
  tags:
    - filesystem
    
- name: Fetch latest stage tarball
  get_url:
    url: "{{ gentoo_install_baseurl }}{{ latest_stage_tarball_url_suffix }}"
    dest: /mnt/gentoo/{{ latest_stage_tarball }}
    tmp_dest: /mnt/gentoo
  tags:
    - filesystem
    
- name: Fetch latest stage tarball's digest
  get_url:
    url: "{{ gentoo_install_baseurl }}{{ latest_stage_tarball_url_suffix }}.DIGESTS.asc"
    dest: /mnt/gentoo/{{ latest_stage_tarball }}.DIGESTS.asc
    tmp_dest: /mnt/gentoo
  tags:
    - filesystem
    
- name: Verify stage3 archive hash
  command: sha512sum -c stage3.sha512
  args:
    chdir: /mnt/gentoo
  register: verify_archive_hash
  failed_when: >
    ": OK" not in verify_archive_hash.stdout
  tags:
    - filesystem
    
- name: Unarchive stage3
  unarchive:
    src: /mnt/gentoo/{{ latest_stage_tarball }}
    dest: /mnt/gentoo
    remote_src: yes
    extra_opts:
      - --xattrs-include='*.*'
      - --numeric-owner
    creates: /mnt/gentoo/etc/gentoo-release
  tags:
    - filesystem

- name: Cleanup stage3
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /mnt/gentoo/{{ latest_stage_tarball }}
    - /mnt/gentoo/{{ latest_stage_tarball }}.DIGESTS.asc
    - /mnt/gentoo/stage3.sha512
  tags:
    - filesystem

- mount:
    path: /mnt/gentoo/proc
    fstype: proc
    src: proc
    state: mounted
  tags:
    - chroot

- mount:
    path: /mnt/gentoo/dev
    src: /dev
    opts: rbind
    state: mounted
    fstype: none
  tags:
    - chroot

- mount:
    path: /mnt/gentoo/sys
    src: /sys
    opts: rbind
    state: mounted
    fstype: none
  tags:
    - chroot

- name: Create resolv.conf
  command: cp -L /etc/resolv.conf /mnt/gentoo/etc/
  args:
    creates: /mnt/gentoo/etc/resolv.conf
  tags:
    - chroot

- name: Install Portage snapshot
  command: chroot /mnt/gentoo bash -c 'source /etc/profile; /usr/bin/emerge-webrsync'
  args:
    creates: /mnt/gentoo/usr/portage/Manifest
  tags:
    - chroot

- name: Set Gentoo profile (amd64 17.0)
  command: chroot /mnt/gentoo bash -c 'source /etc/profile; eselect profile set 12'
  tags:
    - chroot

- name: Set timezone
  command: >
    chroot /mnt/gentoo bash -c
    'cp /usr/share/zoneinfo/{{ timezone }} /etc/localtime; echo "{{ timezone }}" > /etc/timezone'
  tags:
    - chroot

- name: Create hosts file
  template:
    src: hosts
    dest: /mnt/gentoo/etc/hosts
  tags:
    - chroot

- name: Set hostname
  template:
    src: hostname
    dest: /mnt/gentoo/etc/conf.d/hostname
  tags:
    - chroot

- name: Create fstab
  copy:
    src: fstab
    dest: /mnt/gentoo/etc/fstab
  tags:
    - chroot

- name: Create make.conf
  template:
    src: make.conf
    dest: /mnt/gentoo/etc/portage/make.conf
  tags:
    - chroot

- file:
    path: /tmp/base_completed
    state: touch
