---
- stat:
    path: /tmp/parted_is_done
  register: parted_is_done
  tags:
    - storage

- name: Create Grub BIOS Partition
  when: parted_is_done.stat.exists == False
  parted:
    label: gpt
    device: "{{ main_disk }}"
    number: 1
    part_end: 1MiB
    flags: [ bios_grub ]
    state: present
  tags:
    - storage

- name: Create Swap Partition
  when: parted_is_done.stat.exists == False
  parted:
    label: gpt
    device: "{{ main_disk }}"
    number: 2
    part_start: 1MiB
    part_end: "{{ swap_size }}"
    state: present
  tags:
    - storage

- name: Format Swap Partition
  command: "mkswap {{ main_disk }}2"
  tags:
    - storage

- name: Create Root Partition
  when: parted_is_done.stat.exists == False
  parted:
    label: gpt
    device: "{{ main_disk }}"
    part_start: "{{ swap_size }}"
    part_end: 100%
    number: 3
    state: present
  tags:
    - storage

- name: Format Root Partition
  filesystem:
    fstype: "{{ fstype }}"
    dev: "{{ main_disk }}3"
    force: "{{ force_format }}"
  tags:
    - storage

- file:
    path: /tmp/parted_is_done
    state: touch
  tags:
    - storage

- name: Mount root
  mount:
    path: /mnt/gentoo
    src: "{{ main_disk }}3"
    fstab: /tmp/tmp_fstab
    fstype: "{{ fstype }}"
    state: mounted
  tags:
    - storage
