---
- name: Install system packages (syslog, cronie, grub)
  command: chroot /mnt/gentoo bash -c 'source /etc/profile; emerge {{ item.name }}' creates="{{ item.creates }}"
  with_items:
    - name: syslog-ng
      creates: /mnt/gentoo/usr/sbin/syslog-ng
    - name: cronie
      creates: /mnt/gentoo/etc/init.d/cronie
    - name: grub:2
      creates: /mnt/gentoo/usr/sbin/grub-install

- name: Start system packages at boot (syslog, cronie)
  command: chroot /mnt/gentoo bash -c 'rc-update add {{ item }} default'
  with_items:
    - syslog-ng
    - cronie

- name: Configure grub defaults
  copy: src=grub_default dest=/mnt/gentoo/etc/default/grub mode=0644 owner=root group=root

- name: Install grub to boot device ({{ main_disk }})
  command: chroot /mnt/gentoo bash -c 'source /etc/profile; grub-install {{ main_disk }}'

- name: Configure grub
  command: chroot /mnt/gentoo bash -c 'source /etc/profile; grub-mkconfig -o /boot/grub/grub.cfg'

- name: Set root password
  command: chroot /mnt/gentoo bash -c 'source /etc/profile; echo "root:{{ root_passwd }}" | /usr/sbin/chpasswd'

- name: Copy portage config
  copy:
    src: portage/package.use
    dest: /etc/portage/package.use/system

- name: Rebuild @world
  command: chroot /mnt/gentoo bash -c 'source /etc/profile; emerge --update --deep --newuse @world'

- name: configure locales
  lineinfile:
    dest: /etc/locale.gen
    line: "{{ item }}"
  with_items: "{{ gentoo_install_locales }}"

- name: Build locales
  shell: chroot /mnt/gentoo bash -c 'source /etc/profile; /usr/sbin/locale-gen; /usr/sbin/env-update'
  
- name: set default locale
  command: eselect locale set {{ gentoo_install_locale_default }}
